config/routes.rb
Rails.application.routes.draw do
  resources :questions do
    resources :answers, only: [:create, :destroy, :update]
  end

  root to: "questions#index"

  match 'auth/facebook/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/questions'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user

  validates :description,
  presence: true,
  length: { minimum: 50 }

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  belongs_to :user

  validates :title,
  presence: true,
  length: { minimum: 40}

  validates :description,
  presence: true,
  length: { minimum: 150, maximum: 2000}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers

   def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :authorize, except: :create

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.question = @question
    if @answer.save
      redirect_to "/questions/#{@question.id}"
    else
      flash[:notice] = "Could not save your answer."
      redirect_to "/questions/#{@question.id}"
    end
  end

  def update
    if current_user.id == Question.find(params[:question_id]).author.to_i
      answer = Answer.where(best_answer: true).first
      if answer
        answer.best_answer = false
        answer.save
      end
      answer = Answer.find(params[:id])
      answer.best_answer = true
      answer.save
    else
      flash[:notice] = "Permission Denied."
    end
    redirect_to "/questions/#{params[:question_id]}"

  end

  private

  def answer_params
    params.require(:answer).permit(:description)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize

    if current_user.nil?
      flash[:notice] = "Please sign in first"
      redirect_to '/'
    end
  end

  helper_method :current_user, :authorize
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authorize, except: [:index, :show]

  def index
    @questions = Question.order('created_at DESC')
  end

  def new
    # authorize

    @question = Question.new
  end

  def create
    params[:question][:author] = session[:user_id]
    @question = Question.new(question_params)
   if @question.save
      redirect_to "/questions/#{@question.id}"
    else
      flash.now[:notice] = "Could not save your question."
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
  end

  def edit
    # authorize

    @question = Question.find(params[:id])

    if current_user.id != @question.author.to_i
      flash[:notice] = "You are not allowed to edit this question."
      redirect_to "/questions/#{@question.id}"
    end

  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to "/questions/#{@question.id}"
    else
      render :edit
    end
  end

  def destroy

    question = Question.find(params[:id])

    if current_user.id == question.author.to_i
      question.answers.each do |answer|
        answer.destroy
      end
      question.destroy
      redirect_to action: :index
    else
      flash[:notice] = "You are not allowed to delete this question."
      redirect_to "/questions/#{question.id}"
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :description, :author)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rescue Mission</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="user_nav">
    <% if current_user %>
      Welcome <strong><%= current_user.name %></strong>!
      <%= link_to "Sign out", signout_path, id: "sign_out" %>
    <% else %>
      <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
    <% end %>
  </div>
  <% if flash.any? %>
  <div>
    <%= flash[:notice] %>
  </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/questions/edit.html.erb
<h1><%= @question.title %></h1>

<h4>Edit this Question</h4>

 <ul>
    <% @question.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>

<%= form_for @question do |f| %>

  <%= f.label :description %><br>
  <%= f.text_area :description, cols: 80, rows: 20 %><br>

  <%= f.submit %>
<% end %>

<p><%= link_to "Delete Question", @question, method: :delete %></p>

app/views/questions/index.html.erb
<h1>Questions</h1>

<% @questions.each do |question| %>
  <ul>
    <li><%= link_to question.title, question %></li>
  </ul>
<% end %>

<%= link_to 'Ask a New Question', action: :new %>

app/views/questions/new.html.erb
<h1>Ask a Question</h1>

 <ul>
    <% @question.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>

<%= form_for @question do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title, size: 80 %><br>

  <%= f.label :description %><br>
  <%= f.text_area :description, cols: 80, rows: 20 %><br>

  <%= f.submit %>
<% end %>

<p><%= link_to "Back to Questions", questions_path %></p>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<p><%= markdown(@question.description) %></p>

<p><%= link_to "Delete Question", @question, method: :delete %></p>

<p><%= link_to "Edit Question", "/questions/#{@question.id}/edit" %></p>

<h4>Add an Answer</h4>

<%= form_for [@question, @answer] do |f| %>

  <%= f.label :description %><br>
  <%= f.text_area :description, cols: 80, rows: 10 %><br>

  <%= f.submit %>
<% end %>

<h4>Answers</h4>

<% @question.answers.order(best_answer: :desc, created_at: :desc).each do |answer| %>
  <% if answer.best_answer %>
  <p>BEST ANSWER: <%= answer.description %></p>
  <% else %>
  <p><%= answer.description %> <%= button_to 'Mark as Best Answer', question_answer_path(@question, answer), method: :patch %></p>
  <% end %>
<% end %>

<%= link_to "Back to Questions", questions_path %>